<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401073524 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exchange (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, object VARCHAR(255) NOT NULL, message TEXT NOT NULL, create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE services DROP CONSTRAINT services_pkey');
        $this->addSql('ALTER TABLE services RENAME COLUMN id TO srv_id');
        $this->addSql('ALTER TABLE services RENAME COLUMN name TO srv_name');
        $this->addSql('ALTER TABLE services RENAME COLUMN description TO srv_description');
        $this->addSql('ALTER TABLE services RENAME COLUMN create_date TO srv_create_date');
        $this->addSql('ALTER TABLE services RENAME COLUMN update_date TO srv_update_date');
        $this->addSql('ALTER TABLE services ADD PRIMARY KEY (srv_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE availability');
        $this->addSql('DROP TABLE exchange');
        $this->addSql('ALTER TABLE services DROP CONSTRAINT services_pkey');
        $this->addSql('ALTER TABLE services RENAME COLUMN srv_id TO id');
        $this->addSql('ALTER TABLE services RENAME COLUMN srv_name TO name');
        $this->addSql('ALTER TABLE services RENAME COLUMN srv_description TO description');
        $this->addSql('ALTER TABLE services RENAME COLUMN srv_create_date TO create_date');
        $this->addSql('ALTER TABLE services RENAME COLUMN srv_update_date TO update_date');
        $this->addSql('ALTER TABLE services ADD PRIMARY KEY (id)');
    }
}
