<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409150536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (cat_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cat_name VARCHAR(255) NOT NULL, cat_pictures VARCHAR(255) DEFAULT NULL, PRIMARY KEY (cat_id))');
        $this->addSql('CREATE TABLE exchanges (exc_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exc_object VARCHAR(255) NOT NULL, exc_message TEXT NOT NULL, exc_create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (exc_id))');
        $this->addSql('CREATE TABLE services (srv_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, srv_name VARCHAR(255) NOT NULL, srv_description TEXT NOT NULL, srv_create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, srv_update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (srv_id))');
        $this->addSql('CREATE INDEX IDX_7332E16912469DE2 ON services (category_id)');
        $this->addSql('CREATE INDEX IDX_7332E169F675F31B ON services (author_id)');
        $this->addSql('CREATE TABLE "users" (usr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_email VARCHAR(255) NOT NULL, usr_roles JSON NOT NULL, usr_password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, usr_firstname VARCHAR(160) NOT NULL, usr_name VARCHAR(160) NOT NULL, usr_address VARCHAR(255) NOT NULL, usr_postcode VARCHAR(5) NOT NULL, usr_phone VARCHAR(10) NOT NULL, usr_create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, town VARCHAR(60) NOT NULL, PRIMARY KEY (usr_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (usr_email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E16912469DE2 FOREIGN KEY (category_id) REFERENCES categories (cat_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E169F675F31B FOREIGN KEY (author_id) REFERENCES "users" (usr_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE services DROP CONSTRAINT FK_7332E16912469DE2');
        $this->addSql('ALTER TABLE services DROP CONSTRAINT FK_7332E169F675F31B');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE exchanges');
        $this->addSql('DROP TABLE services');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
