<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331124207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE services (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (usr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_name VARCHAR(160) NOT NULL, usr_firstname VARCHAR(160) NOT NULL, usr_address VARCHAR(255) NOT NULL, usr_postcode VARCHAR(5) NOT NULL, usr_town VARCHAR(60) NOT NULL, usr_email VARCHAR(255) NOT NULL, usr_pwd VARCHAR(255) NOT NULL, usr_create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone VARCHAR(10) NOT NULL, PRIMARY KEY (usr_id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE services');
        $this->addSql('DROP TABLE users');
    }
}
